version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "daily"
    time: "15:03"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "15:03"
